image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    command: | 
      dotnet dev-certs https 
      dotnet tool install --global dotnet-ef
      export PATH="$PATH:~/.dotnet/tools"

vscode:
  extensions:
    - muhammad-sammy.csharp
